#!/bin/sh
export QT_QPA_PLATFORMTHEME=qt5ct
picom --experimental-backend &
wal -R
xset r rate 230 100
# setxkbmap -option caps:swapescape

setxkbmap -option caps:ctrl_modifier
xcape -e 'Caps_Lock=Escape'

polybar top &
syncthing &
polybar bottom &
mpd

# Applications, Not to be taken Seriously
brave &
xdotool key Super+2 && alacritty &
