#!/bin/sh

## this script executes many programs (for vim)

if [ -z "$1" ]; then
    echo "No Arguments given"
    exit 0
fi

filename=`echo $1 | cut -d . -f1`
extension=`echo $1 | cut -d . -f2`

case $extension in
    py)      $(which python) . ;;
    lua)     $(which lua) $1 ;;
    cs)      $(which csc) $1 ;;
    pde)     $(which processing-java) --sketch=../$(pwd | rev | cut -d'/' -f1 | rev) --run ;;
    cpp | h) $(which g++) -o $filename -lglfw -lGL -lm -lX11 -lpthread -lXi -lXrandr -ldl $1 && ./$filename ;;
    java)    $(which javac) $1 && $(which java) $filename ;;
    js)      $(which node) $1 ;;
esac
