#!/bin/sh

## This script makes using godot very fast and easy
# vars
GODOT_PROJECT_PATH=$HOME/godotprojects # directory where you save your projects
####

project=`ls $GODOT_PROJECT_PATH | dmenu -i -l 10` # the menu that spawn when you run the script
projectpath=$GODOT_PROJECT_PATH/$project # this is the projectpath

# dont know how to make projects from the command line yet :(
if [ ! -d $projectpath ]; then
    option=`echo -e "yes\nno" | dmenu -p "Create new Project?"`
    if [ $option = yes ]; then
        notify-send "Doesn't work Yet :("
        exit
    else
        notify-send "Aborted New Project Creation"
        exit
    fi
fi

####

godot-mono --editor --path "$projectpath" & # open the editor directly
# sleep 2 # sleep for 2 secs
# xdotool key Super+3 # only for my use, shifts the workspace to ws 3
notify-send --icon=godot "Godot started" "Opened Project \"$project\"" # notify that started

# only works for alacritty, you need to find different commands compatible with your terminal
alacritty --working-directory="$projectpath" -e nvim --listen godothost .
