#!/usr/bin/env bash
set -euo pipefail

cat ~/.config/qtile/config.py \
    | grep 'EK(' \
    | grep -v '# ' \
    | cut -d, -f1,3 \
    | sed  \
        -e 's/ *EK("//' \
        -e 's/,$//'  \
        -e 's/)$//'  \
        -e 's/S/Shift/'  \
        -e 's/C/Control/'  \
        -e 's/M/Super/'  \
        -e 's/-/ + /g' \
        -e 's/"//g' \
        -e 's/[<>]//g' \
        -e 's/, desc=/\t\t\t\t/' |
        yad --text-info --geometry=800x400
