#!/bin/bash

# toggles screenkey on and off

TOGGLE=$HOME/.toggle
if [ ! -e $TOGGLE ]; then
    touch $TOGGLE
    screenkey -s small --opacity 0.9 -t 1 --no-systray &
else
    rm $TOGGLE
    killall screenkey
fi
