#!/bin/sh
export QT_QPA_PLATFORMTHEME=qt5ct
export EDITOR=nvim
export BROWSER=brave

picom --experimental-backend &
wal -R
xset r rate 230 100
# setxkbmap -option caps:swapescape

setxkbmap -option caps:ctrl_modifier
xcape -e 'Caps_Lock=Escape'

polybar top &
#polybar bottom &
#syncthing &
#mpd
#kdeconnect-cli

brave &
alacritty &

xdotool key Super+2
