#!/bin/sh

init="$(($(cat /sys/class/net/[ew]*/statistics/rx_bytes | paste -sd '+')))"
printf "$(date) => Recording bandwidth. Press enter to stop."

read -r lol

fin="$(($(cat /sys/class/net/[ew]*/statistics/rx_bytes | paste -sd '+')))"

printf "$(date) => %4sB of bandwidth used.\\n" $(numfmt --to=iec $(($fin-$init)))
