#!/bin/sh
# To be run from the terminal
# Run script as ". open-script"
# To prevent opening a subshell or something
# https://stackoverflow.com/questions/255414/why-cant-i-change-directories-using-cd-in-a-script

# tmux kill-server
direc=`find $HOME/dox/programming -maxdepth 4 -type d | fzf -i`
if [ -d $direc ]
then
    cd $direc
else
    echo "Error: Not a directory"
    exit
fi
# tmux cause i close this too often, and tmux saves it :)
# sed -i "s|root: .*|root: $direc|" $HOME/.config/tmuxinator/testing.yml
# tmuxinator start testing
#
# neovide --multigrid $direc && exit
#
# simple terminal
nvim $direc
